# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IdusClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IdusClone
  pod 'MaterialComponents/BottomSheet'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'Tabman'
  pod 'XLPagerTabStrip'
  pod 'MSPeekCollectionViewDelegateImplementation'

  target 'IdusCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IdusCloneUITests' do
    # Pods for testing
  end

end
